

ex2 : main_create main_cons main_prod

pipe : 
	g++ -o pipe pipe.cpp

main_create :
	g++ -o main_create main_createur.cpp

main_cons :
	g++ -o main_cons main_consommateur.cpp

main_prod :
	g++ -o main_prod main_producteur.cpp

clean : 
	rm -f pipe main_cons main_create main_prod